_CURRENT_LANG = "es"

def set_lang(lang: str):
    global _CURRENT_LANG
    if lang in STRINGS:
        _CURRENT_LANG = lang

def get_lang() -> str:
    return _CURRENT_LANG

def t(key: str, **kwargs) -> str:
    """
    Translate a key to the current language.
    Supports format placeholders: t("hello_name", name="Pedro")
    Falls back to Spanish if key not found in selected language.
    """
    text = STRINGS.get(_CURRENT_LANG, STRINGS["es"]).get(key)
    if text is None:
        text = STRINGS["es"].get(key, key)
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return text


_ES = {

    "main_menu_title":          "MENÚ PRINCIPAL",
    "continue_game":            "Continuar partida guardada",
    "new_game":                 "Nueva partida",
    "credits":                  "Créditos",
    "quit":                     "Salir",
    "change_language":          "Cambiar idioma / Change language",
    "main_menu_prompt":         "¿Qué hacés?",
    "overwrite_save":           "Hay una partida guardada. ¿La borramos y empezamos de cero?",
    "overwrite_yes":            "Sí, empezar de nuevo (perder todo)",
    "overwrite_no":             "No, volver al menú",

    "lang_title":               "IDIOMA / LANGUAGE",
    "lang_prompt":              "Elegí tu idioma / Choose your language",
    "lang_es":                  "Español",
    "lang_en":                  "English",
    "lang_changed":             "Idioma cambiado a Español.",

    "char_creation_title":      "CREACIÓN DE PERSONAJE",
    "enter_name":               "Nombre de tu personaje (el que van a poner en la lápida)",
    "name_too_short":           "El nombre tiene que tener entre 2 y 20 caracteres. No es mucho pedir.",
    "classes_title":            "CLASES DISPONIBLES — elegí bien, che",
    "class_confirm_yes":        "Sí, quiero esta clase",
    "class_confirm_no":         "Mmm no, mejor elijo otra",
    "class_confirm_prompt":     "¿Confirmamos esta clase?",
    "class_select_prompt":      "¿Cuál es tu clase? (elegí bien)",
    "char_ready":               "{name} el {class_name} da el primer paso hacia la leyenda. O hacia el desastre. Probablemente los dos.",

    "opening_1":                "Las puertas del calabozo más profundo de Aethoria se cierran detrás tuyo.",
    "opening_2":                "No hay antorcha. No hay mapa. Clásico.",
    "opening_3":                "Solo hay oscuridad y lo que sea que se mueve adentro.",
    "opening_4":                "Sos {name}, {class_name}.",
    "opening_5":                "Viniste buscando gloria, tesoros, o venganza. O simplemente no sabías adónde más ir.",
    "opening_6":                "A la mazmorra le chupa un huevo cuál de las tres. Igual te va a comer.",
    "opening_press":            "[ Tu historia arranca ahora. Suerte, que la vas a necesitar. ]",

    "camp_title":               "CAMPAMENTO — ENTRADA A LA MAZMORRA (todavía estás a tiempo de irte)",
    "camp_enter":               "Bajar al Piso {floor} (sin vuelta atrás)",
    "camp_inventory":           "Ver Inventario",
    "camp_stats":               "Ver Stats",
    "camp_skilltree":           "Árbol de Habilidades",
    "camp_shop":                "Tienda de Aventureros",
    "camp_quests":              "Misiones Secundarias",
    "camp_save_quit":           "Guardar y salir (por ahora)",
    "camp_prompt":              "¿Qué hacés?",
    "camp_skills_available":    "{n} para desbloquear",
    "camp_skills_none":         "ninguna disponible",
    "camp_quests_active":       "{n} activas",
    "camp_next_floor":          "Próximo   : Piso {floor} — ¿seguro?",
    "saved_quit":               "Partida guardada. Hasta la próxima, aventurero. Descansá.",
    "game_loaded":              "Partida cargada: {name} el {class_name} nivel {level}. Seguimos.",
    "load_failed":              "No se pudo cargar la partida. Fue, fue.",

    "stats_title":              "STATS",
    "stats_attributes":         "ATRIBUTOS",
    "stats_abilities":          "HABILIDADES",

    "inventory_title":          "INVENTARIO — lo que cargás",
    "inventory_empty":          "La mochila está vacía, ni un alfajor",
    "inventory_equipped":       "EQUIPADO AHORA:",
    "inventory_select":         "¿Qué objeto?",
    "inventory_action":         "¿Qué hacés con esto?",
    "inventory_use":            "Usar ahora",
    "inventory_equip":          "Equipar",
    "inventory_drop":           "Tirar (y chau)",
    "inventory_cancel":         "Cancelar",
    "inventory_back":           "-- Cerrar --",
    "inventory_dropped":        "Tiraste el {item}. Decisión tomada.",
    "inventory_full":           "La mochila está llena. Tirar algo primero, che.",
    "inventory_not_usable":     "{item} no se puede usar de esa manera.",
    "inventory_not_equippable": "{item} no se puede equipar, lamentablemente.",

    "combat_your_turn":         "TU TURNO",
    "combat_enemy_turn":        "TURNO ENEMIGO",
    "combat_action_attack":     "Atacar",
    "combat_action_ability":    "Usar Habilidad",
    "combat_action_potion":     "Usar Poción",
    "combat_action_flee":       "Huir",
    "combat_action_prompt":     "¿Qué hacés?",
    "combat_no_potions":        "No tenés pociones. Previsión cero.",
    "combat_no_abilities":      "No tenés habilidades disponibles. O están en cooldown. O las dos cosas.",
    "combat_flee_success":      "Salís rajando. Sin vergüenza. Estrategia completamente válida.",
    "combat_flee_fail":         "El paso te cortó, che. No hay forma de zafar.",
    "combat_victory":           "VICTORIA! El {enemy} cayó. Bien ahí.",
    "combat_defeat":            "Caíste. La mazmorra se comió otro gil. Eso es todo.",
    "combat_xp_gain":           "  Ganaste {amount} puntos de experiencia. Algo aprendiste.",
    "combat_level_up":          "  *** SUBISTE DE NIVEL, CAMPEÓN! Sos nivel {level} ahora! ***",
    "combat_level_stats":       "  HP: +{hp}  |  MP: +{mp}  |  Te sentís posta.",
    "combat_level_flavor":      "  Tu poder creció. La oscuridad retrocede. Por ahora. Disfrutalo.",
    "combat_gold_found":        "  Encontrás {amount} monedas de oro. No está mal.",
    "combat_item_found":        "  Objeto encontrado: {item} — {msg}",
    "combat_critical":          "¡Golpe crítico! Encontraste el punto débil. Buena puntería.",
    "combat_enemy_critical":    "¡Golpe crítico devastador! Te duele hasta el alma.",
    "combat_evade":             "¡Tu evasión funcionó! El ataque pasó a centímetros. Suertudo.",
    "combat_evade_ability":     "¡Evasión exitosa! La habilidad pasó sin tocarte. De nada.",
    "combat_stunned":           "El {enemy} está aturdido y pierde el turno. ¡Aprovechá!",
    "combat_slain_by":          "  Te liquidó: {enemy}",
    "combat_level_reached":     "  Nivel que llegaste: {level}",
    "combat_kills":             "  Enemigos eliminados: {kills}",
    "combat_gold_grave":        "  Oro que llevabas: {gold} gp. Ahora es de la mazmorra.",
    "combat_dungeon_claims":    "  Los calabozos de Aethoria se tragaron otra alma. Como siempre.",
    "combat_press_enter":       "  [ Presioná ENTER para continuar, si te animás ]",

    "dungeon_map_title":        "MAPA DEL PISO",
    "dungeon_entering":         "[ Entrando a: {name} ]",
    "dungeon_floor_cleared":    "¡Piso {floor} completado! Seguís. Eso dice mucho de vos.",
    "dungeon_boss_doors":       "Las puertas enormes crujen al abrirse. Aire frío inunda el pasillo.",
    "dungeon_boss_stirs":       "Silencio. Pasos. Algo muy antiguo y muy enojado se despierta.",
    "dungeon_boss_sealed":      "La sala se cerró detrás tuyo. No hay salida. Era de esperarse, ¿no?",
    "dungeon_boss_press":       "[ Preparate — el {boss} te espera. Buena suerte, la vas a necesitar. ]",
    "dungeon_stairs":           "La mazmorra tiembla. Aparece una escalera que baja más todavía. Siempre hay más.",
    "dungeon_rest_found":       "Encontrás un rincón tranquilo. Te tirás como si fuera domingo. Merecido.",
    "dungeon_rest_recovered":   "Recuperaste {hp} HP y {mp} MP. Eso es vida.",
    "dungeon_rest_ailments":    "Los estados negativos se van. La mazmorra puede esperar un toque.",
    "dungeon_trap_sense":       "Algo no está bien acá. Una trampa. Claro que hay una trampa.",
    "dungeon_trap_avoided":     "¡Tus reflejos te salvaron! Saltaste justo a tiempo. Que susto, uh.",
    "dungeon_trap_avoided_msg": "¡Trampa evitada! La destreza sirvió para algo.",
    "dungeon_trap_hit":         "¡La trampa se activó! Recibís {damage} de daño. Debiste fijarte mejor.",
    "dungeon_trap_damage":      "Daño de trampa: {damage} HP. Duele.",
    "dungeon_treasure_found":   "¡Encontraste un escondite con cosas! Alguien las dejó acá. Ahora son tuyas.",
    "dungeon_gold_found":       "  Oro: {amount} gp. No está nada mal.",
    "dungeon_take_item":        "Llevar: {item}",
    "dungeon_leave_item":       "Dejarlo acá",
    "dungeon_item_prompt":      "¿Qué hacés con esto?",
    "dungeon_merchant_line":    '"Che, pasá pasá. Mirá esto, posta que te sirve. No te voy a mentir... mucho."',
    "dungeon_altar_prompt":     "[ Ofrecer 20 HP (capaz recibís poder), Dejarlo tranquilo ]",
    "dungeon_altar_power":      "¡El poder oscuro te llenó! +{hp} HP máx, +{atk} ATQ. Raro pero copado.",
    "dungeon_altar_curse":      "¡El altar te rechazó! Quedaste maldito. Era esperable.",
    "dungeon_altar_leave":      "Prudente. El altar te mira irse. Igual no te va a olvidar.",
    "dungeon_altar_event":      "Un altar oscuro pulsa con energía maligna. Algo pide tributo. Siempre hay algo pidiendo algo.",
    "dungeon_fountain_event":   "Una fuente con líquido brillante. Huele a magia antigua. Tomás igual, que queda poco HP.",
    "dungeon_fountain_healed":  "¡Las aguas mágicas te restauraron! El cuerpo y el alma. Un lujo en esta mazmorra.",
    "dungeon_chest_event":      "Un cofre abierto lleno de oro. Algo no cierra. En una mazmorra, rara vez cierra.",
    "dungeon_chest_take":       "Agarrar el oro (YOLO)",
    "dungeon_chest_leave":      "Dejarlo y seguir",
    "dungeon_chest_cursed":     "¡Maldición! Recibís {damage} de daño. Pero el oro es tuyo. Valió la pena.",
    "dungeon_chest_safe":       "Te guardás {gold}gp. Sin maldición. Hoy el universo fue amable.",
    "dungeon_chest_walk":       "Te alejás. El cofre sisea. Claramente una buena decisión.",
    "dungeon_ghost_gift":       '"Tomá esto... ya no me sirve de nada."',
    "dungeon_ghost_item":       "El espíritu te da: {item}. Un gesto copado desde el más allá.",
    "dungeon_ghost_event":      "Un fantasma aparece. El espíritu de un aventurero caído. Tuvo menos suerte que vos.",
    "dungeon_shrine_event":     "Un santuario con runas ofrece una bendición. Parece que te considera digno. Buen día.",
    "dungeon_shrine_prompt":    "¿Qué bendición elegís?",
    "dungeon_shrine_str":       "FUE (+2 Fuerza — para los que resuelven todo a piñas)",
    "dungeon_shrine_dex":       "DES (+2 Destreza — sigiloso y ágil)",
    "dungeon_shrine_int":       "INT (+2 Inteligencia — el libro lo dice)",
    "dungeon_shrine_wis":       "SAB (+2 Sabiduría — que dicen los que saben)",
    "dungeon_shrine_con":       "CON (+2 Constitución — aguantá más, que falta)",
    "dungeon_shrine_granted":   "¡El santuario te otorga +{val} {stat}! Se nota que eras el elegido.",
    "dungeon_merchant_stock":   "CALIDAD GARANTIZADA. MAYORMENTE.",
    "dungeon_no_gold":          "Con esa guita no alcanza, flaco.",
    "dungeon_nothing_sell":     "No tenés nada para vender. Ni un hueso.",
    "dungeon_sold":             "Vendiste {item} por {price}gp. Trato hecho.",
    "dungeon_bought":           "Compraste {item}. Buena inversión.",
    "dungeon_bag_full":         "La mochila está llena, flaco.",
    "dungeon_altar_offer":      "Ofrecer 20 HP (capaz recibís poder)",
    "dungeon_altar_skip":       "Dejarlo tranquilo",

    "shop_title":               "TIENDA DE AVENTUREROS — AETHORIA",
    "shop_tagline":             '"Precios honestos. Mayormente. Bueno, razonables."',
    "shop_stock_label":         "STOCK DISPONIBLE:",
    "shop_no_stock":            "Sin stock. Volvé mañana.",
    "shop_no_afford":           "(sin guita)",
    "shop_buy":                 "Comprar",
    "shop_sell":                "Vender",
    "shop_exit":                "Salir de la tienda",
    "shop_prompt":              "¿Qué hacés?",
    "shop_buy_prompt":          "¿Qué comprás?",
    "shop_sell_prompt":         "¿Qué vendés?",
    "shop_cancel":              "-- Cancelar --",
    "shop_no_gold":             "Con esa guita no alcanza, flaco.",
    "shop_inventory_full":      "La mochila está llena. Te devuelvo la guita.",
    "shop_bought":              "Compraste: {item}. Buena elección.",
    "shop_sold":                "Vendiste {item} por {price}gp. Trato hecho.",
    "shop_nothing_sell":        "No tenés nada para vender. Ni un clavo.",
    "shop_refreshed":           "El stock de la tienda se renovó. Llegaron novedades.",

    "quest_log_title":          "REGISTRO DE MISIONES",
    "quest_completed_count":    "Completadas: {n}",
    "quest_active_count":       "Activas: {n}",
    "quest_in_progress":        "EN CURSO:",
    "quest_completed_header":   "COMPLETADAS:",
    "quest_none_active":        "No hay misiones activas. Bastante raro.",
    "quest_none_completed":     "Ninguna todavía. A trabajar.",
    "quest_completed_msg":      "  *** MISIÓN COMPLETADA: {name} ***",
    "quest_reward_line":        "  Recompensa: {gold} oro + {xp} XP",
    "quest_reward_item":        "  Objeto: {item}",
    "quest_received":           "  Recibís: {item}",

    "skill_tree_title":         "ÁRBOL DE HABILIDADES — {class_name}",
    "skill_unlocked":           "[DESBLOQUEADA]",
    "skill_available":          "[DISPONIBLE]",
    "skill_locked":             "[BLOQUEADA — {reason}]",
    "skill_req":                "Req: Nivel {level}",
    "skill_tier_base":          "BASE",
    "skill_tier_advanced":      "AVANZADA",
    "skill_tier_elite":         "ÉLITE",
    "skill_unlock_prompt":      "¿Qué habilidad desbloqueás?",
    "skill_back":               "-- Volver --",
    "skill_no_available":       "[ No hay habilidades para desbloquear ahora. Subí de nivel. ]",
    "skill_unlocked_msg":       "¡Desbloqueaste: {name}!",
    "skill_now_available":      "  La habilidad ya está disponible en combate.",

    "victory_banner":           "V I C T O R I A  —  LO LOGRASTE",
    "victory_1":                "Conquistaste los Calabozos de Aethoria. En serio. Nadie lo esperaba.",
    "victory_2":                "La oscuridad final fue derrotada. Por vos. Que clase de loco.",
    "victory_3":                "Tu nombre va a quedar grabado en piedra. O en un grupo de WhatsApp. Es lo mismo.",
    "victory_stats":            "ESTADÍSTICAS FINALES",
    "victory_name":             "  Nombre : {name}",
    "victory_class":            "  Clase  : {class_name}  Nivel {level}",
    "victory_kills":            "  Bajas  : {kills}",
    "victory_gold":             "  Oro    : {gold} gp — que bien gastaste",
    "victory_press":            "[ Una leyenda nació. Vos. ]",
    "gameover_banner":          "F I N   D E L   J U E G O  —  hasta la próxima",
    "gameover_1":               "Caíste. La mazmorra se comió otro gil. Eso es todo.",
    "gameover_2":               "Tus huesos se quedan acá con los de los demás. Buena compañía.",
    "gameover_char":            "  {name} el {class_name} — Nivel {level}",
    "gameover_stats":           "  Enemigos eliminados: {kills}  |  Pisos completados: {floors}",
    "gameover_gold":            "  Oro que te llevaste a la tumba: {gold} gp. Inútil, pero tuyo.",

    "credits_title":            "DUNGEONS OF AETHORIA — Créditos",
    "credits_built":            "  Creado con Python 3.11+ y mucho mate",
    "credits_inspired":         "  Inspirado en los RPGs de texto de los años 80",
    "credits_dnd":              "  y los reglamentos originales de Dungeons & Dragons",
    "credits_thanks":           "  Gracias por jugar. En serio.",
    "credits_quote_1":          "  'No todos los que vagan por mazmorras están perdidos.'",
    "credits_quote_2":          "  'La mayoría sí. Completamente.'",
    "quit_1":                   "La antorcha se apaga. La mazmorra espera. Siempre espera.",
    "quit_2":                   "Hasta la próxima, aventurero. Cuando quieras volvés.",

    "invalid_option":           "Opción inválida. De nuevo, dale.",
    "press_enter":              "[ Presioná ENTER para continuar ]",


    "class_desc_guerrero":  "Maestro del combate cuerpo a cuerpo. Resistente y poderoso.",
    "class_desc_mago":      "Lanzador de hechizos. Frágil pero devastadoramente poderoso.",
    "class_desc_picaro":    "Sombra y daga. Ataca rápido, ataca primero, ataca letal.",
    "class_desc_paladin":   "Guerrero sagrado. Cura aliados y golpea el mal con poder divino.",
    "class_desc_arquero":   "Maestro del combate a distancia. Preciso, veloz y letal desde lejos.",
    "class_desc_barbaro":   "Furia pura. Más daño cuanto más herido esté. Sin límites.",
    "class_desc_monje":     "Combatiente sin armas. Velocidad y disciplina sobre fuerza bruta.",
    "class_desc_explorador":"Rastreador y trampero. Letal por sorpresa y maestro del terreno.",
    "class_desc_hechicero": "Magia caótica e impredecible. Alto riesgo, alta recompensa.",
    "class_desc_brujo":     "Pactos oscuros con entidades antiguas. Poder a precio de sangre.",

    "ab_guerrero_1_name": "Golpe Poderoso",
    "ab_guerrero_1_desc": "Ataque devastador que ignora parte de la armadura.",
    "ab_guerrero_2_name": "Segunda Oportunidad",
    "ab_guerrero_2_desc": "Te recuperás con 30 HP cuando estás cerca de morir.",
    "ab_guerrero_3_name": "Golpe Torbellino",
    "ab_guerrero_3_desc": "Atacás a todos los enemigos en el turno.",

    "ab_mago_1_name": "Bola de Fuego",
    "ab_mago_1_desc": "Proyectil de fuego que quema al enemigo.",
    "ab_mago_2_name": "Escudo Arcano",
    "ab_mago_2_desc": "Barrera mágica que reduce el daño recibido.",
    "ab_mago_3_name": "Rayo de Tormenta",
    "ab_mago_3_desc": "Rayo que ignora defensa y aturde al enemigo.",

    "ab_picaro_1_name": "Puñalada Trasera",
    "ab_picaro_1_desc": "Ataque sorpresa con alto daño crítico.",
    "ab_picaro_2_name": "Veneno en la Hoja",
    "ab_picaro_2_desc": "Envenena al enemigo causando daño continuo.",
    "ab_picaro_3_name": "Sombra Fugaz",
    "ab_picaro_3_desc": "Te volvés esquivo por un turno, evitando ataques.",

    "ab_paladin_1_name": "Golpe Sagrado",
    "ab_paladin_1_desc": "Ataque cargado de energía divina. Extra vs. no-muertos.",
    "ab_paladin_2_name": "Curación Divina",
    "ab_paladin_2_desc": "Restaurás 45 HP con la gracia divina.",
    "ab_paladin_3_name": "Aura Sagrada",
    "ab_paladin_3_desc": "Aura que reduce el daño recibido por 3 turnos.",

    "ab_arquero_1_name": "Disparo Certero",
    "ab_arquero_1_desc": "Flecha precisa que siempre da en el blanco.",
    "ab_arquero_2_name": "Flecha Envenenada",
    "ab_arquero_2_desc": "Disparo que envenena al enemigo.",
    "ab_arquero_3_name": "Ojo de Halcón",
    "ab_arquero_3_desc": "Analizás las debilidades del enemigo para los próximos ataques.",

    "ab_barbaro_1_name": "Golpe Brutal",
    "ab_barbaro_1_desc": "Ataque masivo que aplasta defensas.",
    "ab_barbaro_2_name": "Modo Furia",
    "ab_barbaro_2_desc": "Entrás en berserker: más daño pero sin defensa.",
    "ab_barbaro_3_name": "Grito de Guerra",
    "ab_barbaro_3_desc": "Aterrorizás al enemigo, paralizándolo un turno.",

    "ab_monje_1_name": "Golpe de Chi",
    "ab_monje_1_desc": "Golpe de energía pura que ignora armadura.",
    "ab_monje_2_name": "Curación Interna",
    "ab_monje_2_desc": "Meditás para restaurar 35 HP.",
    "ab_monje_3_name": "Lluvia de Golpes",
    "ab_monje_3_desc": "Cinco golpes rápidos que superan defensas.",

    "ab_explorador_1_name": "Trampa de Caza",
    "ab_explorador_1_desc": "Colocás una trampa que causa daño y ralentiza.",
    "ab_explorador_2_name": "Ataque Furtivo",
    "ab_explorador_2_desc": "Ataque sorpresa con daño doble.",
    "ab_explorador_3_name": "Marca del Rastreador",
    "ab_explorador_3_desc": "Marcás al enemigo para aumentar el daño futuro.",

    "ab_hechicero_1_name": "Caos Arcano",
    "ab_hechicero_1_desc": "Hechizo aleatorio con efectos impredecibles.",
    "ab_hechicero_2_name": "Drenaje de Maná",
    "ab_hechicero_2_desc": "Absorbés la energía del enemigo para curarte.",
    "ab_hechicero_3_name": "Tormenta de Caos",
    "ab_hechicero_3_desc": "Explosión mágica masiva con múltiples efectos.",

    "ab_brujo_1_name": "Maldición Oscura",
    "ab_brujo_1_desc": "Maldición que drena la vida del enemigo por turnos.",
    "ab_brujo_2_name": "Pacto de Sangre",
    "ab_brujo_2_desc": "Sacrificás vida propia para un ataque devastador.",
    "ab_brujo_3_name": "Invocar Sombra",
    "ab_brujo_3_desc": "Invocás una sombra que ataca en tu nombre.",

    "room_combat":   "[ ENCUENTRO ]",
    "room_treasure": "[ TESORO ]",
    "room_rest":     "[ DESCANSO ]",
    "room_merchant": "[ MERCADER ]",
    "room_trap":     "[ TRAMPA ]",
    "room_mystery":  "[ MISTERIO ]",
    "room_boss":     "[ !! JEFE !! ]",
    "room_generic":  "[ HABITACIÓN ]",

    "floor_1":  "Las criptas de arriba. Los bichos son flojos pero no te confiés. Nunca.",
    "floor_2":  "Los salones funerarios. Los muertos se ponen cada vez más inquietos. Spoiler: empeora.",
    "floor_3":  "Las madrigueras. Algo organizado vive acá y ya sabe que llegaste. Mal comienzo.",
    "floor_4":  "Las galerías de sombra. La luz muere acá. Los monstruos se ponen más valientes.",
    "floor_5":  "Las minas profundas. Las excavaron tipos que encontraron algo que no debían. Así terminaron.",
    "floor_6":  "Las bóvedas malditas. El mal antiguo sale de las mismas piedras. Arquitectura peligrosa.",
    "floor_7":  "Los corredores demoníacos. No todos los que entraron acá eran humanos. Algunos ya no lo son.",
    "floor_8":  "Los salones del abismo. La realidad se siente delgada. Algo te mira desde las paredes.",
    "floor_9":  "El descenso final. El dueño de la mazmorra espera. Todos los caminos terminan acá.",
    "floor_10": "PROFUNDIDAD DESCONOCIDA. Los mapas llegan hasta acá. Las leyendas también. ¿Vos?",

    "room_desc_combat_1": "La antorcha titila. Algo se mueve al fondo del pasillo. Clásico.",
    "room_desc_combat_2": "Llegó un olor horrible. Algo vive acá y está al tanto de tu visita.",
    "room_desc_combat_3": "Huesos antiguos crujen bajo tus pies. Quien hizo este cuarto todavía cree que es suyo.",
    "room_desc_combat_4": "Gruñidos bajos desde la oscuridad. Agarrás el arma. Respirás. Solo dos sirven.",
    "room_desc_combat_5": "Las paredes tienen raspaduras frescas. Algo con garras estuvo acá hace muy poco.",
    "room_desc_treasure_1": "Un brillo metálico desde abajo de los escombros. Puede ser oro. Puede ser trampa. Fifty-fifty.",
    "room_desc_treasure_2": "Un cofre de piedra tallada, intacto. Nadie lo abrió. Eso puede ser bueno o muy malo.",
    "room_desc_treasure_3": "Los restos de un aventurero con menos suerte. Sus cosas siguen acá. Los muertos no usan equipo.",
    "room_desc_treasure_4": "Una piedra suelta revela un hueco escondido. Adentro: oportunidad. O arañas. Probablemente las dos.",
    "room_desc_rest_1": "Un rincón seco con los restos de un fogón viejo. Seguro como un domingo después del asado.",
    "room_desc_rest_2": "Agua limpia que gotea de una grieta en la piedra. Fría, cristalina y, en este lugar, casi un milagro.",
    "room_desc_rest_3": "La mazmorra se abre en una sala tranquila. Por un momento, nada quiere matarte. Aprovechalo.",
    "room_desc_merchant_1": "Un tipo detrás de un puesto improvisado, totalmente tranquilo en medio de la mazmorra.",
    "room_desc_merchant_2": "Una caravana de mercader, acá, en el pasillo de la mazmorra. Sin explicaciones. Funciona.",
    "room_desc_trap_1": "El piso está muy liso. Demasiado liso. En una mazmorra eso no es buena señal.",
    "room_desc_trap_2": "Hilos finísimos capturan la luz de la antorcha. Parás en seco. Muy repentinamente cuidadoso.",
    "room_desc_trap_3": "Una placa de presión tiene una inscripción en tres idiomas muertos: 'Volvete'. Mensaje claro.",
    "room_desc_mystery_1": "Un altar raro en el centro de la sala, con símbolos que pulsan en luz tenue.",
    "room_desc_mystery_2": "Un espejo apoyado en la pared. Tu reflejo no se mueve al mismo tiempo que vos. Clásico.",
    "room_desc_mystery_3": "Palabras talladas en el piso: 'Elegí bien. O directamente no elegís'. Filosofía de mazmorra.",
    "room_desc_boss": "Al final de un pasillo largo, unas puertas enormes están entreabiertas. Algo respira del otro lado.",

    "combat_start":         "  [ El combate comienza... ]",
    "combat_turn":          "Turno",
    "combat_your_action":   "Tu turno",
    "combat_enter_combat":  "Entrar en combate",
    "combat_check_inv":     "Ver inventario primero",
    "combat_ability_prompt":"Habilidad",
    "combat_use_potion":    "Usar pocion",
    "combat_cancel":        "-- Cancelar --",
    "combat_quick_status":  "ESTADO RÁPIDO",
    "combat_status_rest":   "ESTADO AL DESCANSAR",
    "combat_merchant_title":"TIENDA DEL MERCADER",
    "combat_buy":           "Comprar",
    "combat_sell":          "Vender",
    "combat_exit":          "Salir",
    "combat_buy_prompt":    "Comprar",
    "combat_sell_prompt":   "Vender",
    "combat_gold_label":    "Tu Oro",
    "combat_heal_recover":  "You recover {n} HP.",

    "inv_empty_msg":        "La mochila está vacía. Literal nada.",
    "inv_close":            "-- Cerrar --",
    "inv_select":           "¿Qué objeto?",
    "inv_action_use":       "Usar ahora",
    "inv_action_equip":     "Equipar",
    "inv_action_drop":      "Tirar (y chau)",
    "inv_action_cancel":    "Cancelar",
    "inv_action_prompt":    "¿Qué hacés con esto?",
    "inv_dropped":          "Tiraste el {item}. Decisión tomada.",
    "inv_empty_slot":       "-- vacio --",
    "inv_weapon_label":     "Arma",
    "inv_armor_label":      "Armadura",
    "inv_ring_label":       "Anillo",
    "inv_rarity_label":     "Rareza",
    "inv_heal_label":       "Cura",
    "inv_mana_label":       "Maná",


    "ui_clase_header":     "  {'CLASE':<14} {'HP':>4} {'MP':>4} {'Principal':<10} {'Descripcion'}",
    "ui_base_stats":       "  ESTADÍSTICAS BASE",
    "ui_abilities":        "  HABILIDADES",
    "ui_attributes":       "  ATRIBUTOS",
    "ui_start_weapon":     "  Arma inicial",
    "ui_start_armor":      "  Armadura inicial",
    "ui_stat_primary":     "Stat principal",
    "ui_equipped_weapon":  "  Arma",
    "ui_equipped_armor":   "  Armadura",
    "ui_equipped_ring":    "  Anillo",
    "ui_class_label":      "CLASE",
    "ui_hp_label":         "HP",
    "ui_mp_label":         "MP",
    "ui_principal_label":  "Principal",
    "ui_desc_label":       "Descripcion",
    "ui_nivel_label":      "Nivel",
    "ui_oro_label":        "Oro",
    "ui_bajas_label":      "Bajas",
    "ui_pisos_label":      "Pisos",
    "ui_habilidades_label":"Habilidades",
    "ui_misiones_label":   "Misiones",

    "lore_guerrero":  "Nació peleando y nunca paró. Tiene más cicatrices que el auto del tío de un amigo. No estudió mucho, pero lo que sabe lo sabe con el cuerpo. Especialmente el dolor ajeno.",
    "lore_mago":      "Pasó veinte años estudiando en la Torre Arcana. No consiguió laburo en su especialidad. Ahora tira bolas de fuego en una mazmorra. Algo es algo.",
    "lore_picaro":    "Creció en el barrio bravo y aprendió rápido que el que pega primero, pega dos veces. Opera desde las sombras, básicamente lo mismo que hacer las cosas a último momento pero con más dramatismo.",
    "lore_paladin":   "Hizo el juramento solemne de defender la Luz. Lo cumple, en general. Los no-muertos le tienen pánico. Los vivos también, pero por otras razones. Es un poco intenso en los asados.",
    "lore_arquero":   "Creció en el bosque y nunca más salió. Come frutos silvestres, habla poco y dispara mejor que nadie. No lo invités a cumpleaños — va a aparecer desde atrás de un árbol.",
    "lore_barbaro":   "Viene de un lugar muy frío donde no hay mucho que hacer aparte de enojarse. No tiene estrategia. No necesita una. Su plan es ir para adelante hasta que algo pare. Generalmente no es él.",
    "lore_monje":     "Meditó diez mil horas para encontrar la paz interior. La encontró. Resulta que la paz interior se parece mucho a cinco piñas consecutivas en la cara. Filosofía profunda.",
    "lore_explorador":"Lee la mazmorra como si fuera el subte: sabe exactamente cuándo viene el peligro, dónde están las salidas y cuál pasillo huele peor. Prefiere ir solo. Los otros hacen ruido.",
    "lore_hechicero": "La magia le salió sola, sin estudiar. A sus compañeros de escuela los ponía nerviosos. No controla del todo lo que hace. El 65% de las veces sale bien. El otro 35% también es interesante.",
    "lore_brujo":     "Le rezó a algo en la oscuridad y eso le contestó. No sabe bien qué fue. Prefiere no preguntar. El alquiler no se paga solo y los pactos oscuros tienen mejores condiciones que los bancos.",

    "desc_goblin":         "Un goblin flacucho y verdoso con un cuchillo más oxidado que los caños de tu edificio. Parece que no comió en tres días. Igual te va a atacar.",
    "desc_goblin_shaman":  "Un goblin jorobado con huesos colgando por todos lados. Claramente el intelectual del grupo. Eso no lo hace menos peligroso, sí más raro.",
    "desc_giant_rat":      "Una rata del tamaño de un perro mediano. La encontraste en la mazmorra pero podría ser perfectamente del subte de la línea B.",
    "desc_skeleton":       "Huesos pegados con magia oscura y ganas de molestar. El cuchillo está más oxidado que una heladera de los 90. Pero igual duele.",
    "desc_orc":            "Un orco enorme con colmillos y una armadura de hierro que claramente no limpió nunca. Huele a sangre y a algo que preferís no identificar.",
    "desc_dark_elf":       "Una figura elegante de seda negra con dos dagas envenenadas. Vestida mejor que vos. Mucho mejor. Algo que también duele, pero diferente.",
    "desc_zombie_knight":  "Fue noble, ahora es un horror podrido con armadura oxidada. Igual tiene más postura que la mayoría. La muerte no le quitó el porte, lamentablemente.",
    "desc_dungeon_witch":  "Una bruja riéndose sola rodeada de humo verde. El caldero burbujea con algo que definitivamente no es mate. Claramente le va bien en lo suyo.",
    "desc_vampire":        "Pálido, frío y con aires de superioridad. Tiene siglos de experiencia haciéndote sentir inferior. Como ese compañero de trabajo pero con colmillos.",
    "desc_stone_golem":    "Dos metros y medio de granito animado con runas brillando en el pecho. No corre. No habla. No negocia. Simplemente viene hacia vos. Tranquilamente.",
    "desc_lesser_demon":   "Una criatura de fuego y odio puro con alas de cuero quemado. Tiene los ojos como brasas y la actitud de alguien a quien le cancelaron el vuelo y perdió las valijas.",
    "desc_dragon":         "Un dragón enorme. En serio, es GRANDE. No, más grande que eso. Llevás toda la mazmorra pensando que el final iba a ser manejable. Error de cálculo.",
    "desc_lich":           "Fue el mejor mago del mundo y eligió la inmortalidad. Ahora es un esqueleto con actitud. Morirse hubiera sido más elegante, pero nadie le preguntó.",
    "desc_archfiend":      "El verdadero dueño de la mazmorra. Tres siglos encerrado acá abajo. Está de mal humor, con razón. Vos sos lo primero que va a ver al salir. Mala suerte.",
}


_EN = {

    "main_menu_title":          "MAIN MENU",
    "continue_game":            "Continue saved game",
    "new_game":                 "New game",
    "credits":                  "Credits",
    "quit":                     "Quit",
    "change_language":          "Cambiar idioma / Change language",
    "main_menu_prompt":         "What do you do?",
    "overwrite_save":           "There's a saved game. Overwrite it and start fresh?",
    "overwrite_yes":            "Yes, start over (lose everything)",
    "overwrite_no":             "No, go back",

    "lang_title":               "IDIOMA / LANGUAGE",
    "lang_prompt":              "Elegí tu idioma / Choose your language",
    "lang_es":                  "Español",
    "lang_en":                  "English",
    "lang_changed":             "Language changed to English.",

    "char_creation_title":      "CHARACTER CREATION",
    "enter_name":               "Your character's name (the one that goes on the tombstone)",
    "name_too_short":           "Name must be between 2 and 20 characters. Not a lot to ask.",
    "classes_title":            "AVAILABLE CLASSES — choose wisely",
    "class_confirm_yes":        "Yes, I want this class",
    "class_confirm_no":         "Hmm no, let me choose again",
    "class_confirm_prompt":     "Confirm this class?",
    "class_select_prompt":      "Which class? (choose wisely)",
    "char_ready":               "{name} the {class_name} takes their first step toward legend. Or disaster. Probably both.",

    "opening_1":                "The gates of Aethoria's deepest dungeon close behind you.",
    "opening_2":                "No torch. No map. Classic.",
    "opening_3":                "There is only darkness — and whatever stirs within it.",
    "opening_4":                "You are {name}, {class_name}.",
    "opening_5":                "You came seeking glory, treasure, or vengeance. Or you simply had nowhere else to go.",
    "opening_6":                "The dungeon does not care which. It will try to kill you regardless.",
    "opening_press":            "[ Your story begins now. Good luck — you'll need it. ]",

    "camp_title":               "CAMP — DUNGEON ENTRANCE (you can still turn back)",
    "camp_enter":               "Descend to Floor {floor} (no turning back)",
    "camp_inventory":           "View Inventory",
    "camp_stats":               "View Stats",
    "camp_skilltree":           "Skill Tree",
    "camp_shop":                "Adventurer's Shop",
    "camp_quests":              "Side Quests",
    "camp_save_quit":           "Save and quit (for now)",
    "camp_prompt":              "What do you do?",
    "camp_skills_available":    "{n} to unlock",
    "camp_skills_none":         "none available",
    "camp_quests_active":       "{n} active",
    "camp_next_floor":          "Next      : Floor {floor} — are you sure?",
    "saved_quit":               "Game saved. Until next time, adventurer.",
    "game_loaded":              "Game loaded: {name} the {class_name} level {level}. Let's continue.",
    "load_failed":              "Could not load saved game.",

    "stats_title":              "STATS",
    "stats_attributes":         "ATTRIBUTES",
    "stats_abilities":          "ABILITIES",

    "inventory_title":          "INVENTORY — what you're carrying",
    "inventory_empty":          "Your pack is empty. Not even a snack.",
    "inventory_equipped":       "CURRENTLY EQUIPPED:",
    "inventory_select":         "Which item?",
    "inventory_action":         "What do you do with this?",
    "inventory_use":            "Use now",
    "inventory_equip":          "Equip",
    "inventory_drop":           "Discard (gone forever)",
    "inventory_cancel":         "Cancel",
    "inventory_back":           "-- Close --",
    "inventory_dropped":        "You discard the {item}. Decision made.",
    "inventory_full":           "Your pack is full. Drop something first.",
    "inventory_not_usable":     "{item} cannot be used that way.",
    "inventory_not_equippable": "{item} cannot be equipped.",

    "combat_your_turn":         "YOUR TURN",
    "combat_enemy_turn":        "ENEMY TURN",
    "combat_action_attack":     "Attack",
    "combat_action_ability":    "Use Ability",
    "combat_action_potion":     "Use Potion",
    "combat_action_flee":       "Flee",
    "combat_action_prompt":     "What do you do?",
    "combat_no_potions":        "You have no potions.",
    "combat_no_abilities":      "No abilities available — all on cooldown.",
    "combat_flee_success":      "You vanish into the shadows. No shame in it. Completely valid strategy.",
    "combat_flee_fail":         "Your escape is cut off! There's no way out.",
    "combat_victory":           "VICTORY! The {enemy} falls before you!",
    "combat_defeat":            "You have fallen. The dungeon claims another soul.",
    "combat_xp_gain":           "  You gain {amount} experience points.",
    "combat_level_up":          "  *** LEVEL UP! You are now level {level}! ***",
    "combat_level_stats":       "  HP: +{hp}  |  MP: +{mp}",
    "combat_level_flavor":      "  Your power grows. The darkness retreats — for now.",
    "combat_gold_found":        "  You find {amount} gold coins.",
    "combat_item_found":        "  Item found: {item} — {msg}",
    "combat_critical":          "Critical strike! You find a vulnerable point!",
    "combat_enemy_critical":    "A devastating critical hit!",
    "combat_evade":             "Your evasion saves you — the attack misses completely!",
    "combat_evade_ability":     "Your evasion saves you from the ability!",
    "combat_stunned":           "{enemy} is stunned and loses their turn!",
    "combat_slain_by":          "  Slain by: {enemy}",
    "combat_level_reached":     "  Level reached: {level}",
    "combat_kills":             "  Enemies slain: {kills}",
    "combat_gold_grave":        "  Gold carried to the grave: {gold} gp",
    "combat_dungeon_claims":    "  The Dungeons of Aethoria swallow another soul...",
    "combat_press_enter":       "  [ Press ENTER to continue ]",

    "dungeon_map_title":        "FLOOR MAP",
    "dungeon_entering":         "[ Entering: {name} ]",
    "dungeon_floor_cleared":    "Floor {floor} cleared! You press deeper.",
    "dungeon_boss_doors":       "The massive doors groan open. Cold air floods the corridor.",
    "dungeon_boss_stirs":       "Silence. Then footsteps. Something ancient stirs.",
    "dungeon_boss_sealed":      "The boss room seals behind you — there is no escape!",
    "dungeon_boss_press":       "[ Prepare yourself — {boss} awaits. Good luck. ]",
    "dungeon_stairs":           "The dungeon trembles. A stairway descends further into darkness.",
    "dungeon_rest_found":       "You find a safe spot to rest and tend your wounds.",
    "dungeon_rest_recovered":   "You recover {hp} HP and {mp} MP.",
    "dungeon_rest_ailments":    "Ailments fade as you rest. The dungeon waits.",
    "dungeon_trap_sense":       "The floor ahead is smooth — too smooth. Something is wrong.",
    "dungeon_trap_avoided":     "Your quick reflexes save you — you leap aside just in time!",
    "dungeon_trap_avoided_msg": "Trap avoided! (DEX check passed)",
    "dungeon_trap_hit":         "The trap triggers! You take {damage} damage!",
    "dungeon_trap_damage":      "Trap damage: {damage} HP",
    "dungeon_treasure_found":   "You discover a cache of items!",
    "dungeon_gold_found":       "  Gold: {amount} gp",
    "dungeon_take_item":        "Take: {item}",
    "dungeon_leave_item":       "Leave it",
    "dungeon_item_prompt":      "What do you do with this?",
    "dungeon_merchant_line":    '"Ah, a customer! Come, come — see my wares. I ask only gold."',
    "dungeon_altar_prompt":     "[ Offer 20 HP (may receive great power), Leave it alone ]",
    "dungeon_altar_power":      "Dark power flows into you! +{hp} Max HP, +{atk} ATK",
    "dungeon_altar_curse":      "The altar rejects you! You are cursed!",
    "dungeon_altar_leave":      "Wise. The altar watches you leave.",
    "dungeon_altar_event":      "A dark altar pulses with malevolent energy. Something demands tribute.",
    "dungeon_fountain_event":   "A fountain flows with shimmering liquid. It smells of ancient magic.",
    "dungeon_fountain_healed":  "The magical waters restore your body and spirit!",
    "dungeon_chest_event":      "A chest sits open, filled with gold — but something feels wrong.",
    "dungeon_chest_take":       "Take the gold",
    "dungeon_chest_leave":      "Leave it",
    "dungeon_chest_cursed":     "A curse erupts! You take {damage} damage — but keep the gold!",
    "dungeon_chest_safe":       "You pocket {gold}gp. No curse today.",
    "dungeon_chest_walk":       "You walk away. The chest hisses.",
    "dungeon_ghost_gift":       '"Take this... I have no further use for it."',
    "dungeon_ghost_item":       "The spirit gives you: {item}",
    "dungeon_ghost_event":      "A ghostly figure materializes — the spirit of a fallen adventurer.",
    "dungeon_shrine_event":     "A shrine carved with runes offers a boon to the worthy.",
    "dungeon_shrine_prompt":    "Choose your blessing",
    "dungeon_shrine_str":       "STR (+2 Strength)",
    "dungeon_shrine_dex":       "DEX (+2 Dexterity)",
    "dungeon_shrine_int":       "INT (+2 Intelligence)",
    "dungeon_shrine_wis":       "WIS (+2 Wisdom)",
    "dungeon_shrine_con":       "CON (+2 Constitution)",
    "dungeon_shrine_granted":   "The shrine grants you +{val} {stat}!",
    "dungeon_merchant_stock":   "QUALITY GUARANTEED. MOSTLY.",
    "dungeon_no_gold":          "You don't have enough gold.",
    "dungeon_nothing_sell":     "You have nothing to sell.",
    "dungeon_sold":             "Sold {item} for {price}gp.",
    "dungeon_bought":           "Bought {item}.",
    "dungeon_bag_full":         "Your pack is full.",
    "dungeon_altar_offer":      "Offer 20 HP (may receive great power)",
    "dungeon_altar_skip":       "Leave it alone",

    "shop_title":               "ADVENTURER'S SHOP — AETHORIA",
    "shop_tagline":             '"Honest prices. Mostly. Well, reasonable."',
    "shop_stock_label":         "AVAILABLE STOCK:",
    "shop_no_stock":            "Out of stock. Come back later.",
    "shop_no_afford":           "(can't afford)",
    "shop_buy":                 "Buy",
    "shop_sell":                "Sell",
    "shop_exit":                "Leave shop",
    "shop_prompt":              "What do you do?",
    "shop_buy_prompt":          "What do you buy?",
    "shop_sell_prompt":         "What do you sell?",
    "shop_cancel":              "-- Cancel --",
    "shop_no_gold":             "You don't have enough gold.",
    "shop_inventory_full":      "Your pack is full. Refunding your gold.",
    "shop_bought":              "Bought: {item}. Good choice.",
    "shop_sold":                "Sold {item} for {price}gp. Deal done.",
    "shop_nothing_sell":        "You have nothing to sell.",
    "shop_refreshed":           "Shop stock has been refreshed. New arrivals.",

    "quest_log_title":          "QUEST LOG",
    "quest_completed_count":    "Completed: {n}",
    "quest_active_count":       "Active: {n}",
    "quest_in_progress":        "IN PROGRESS:",
    "quest_completed_header":   "COMPLETED:",
    "quest_none_active":        "No active quests.",
    "quest_none_completed":     "None yet. Get to work.",
    "quest_completed_msg":      "  *** QUEST COMPLETED: {name} ***",
    "quest_reward_line":        "  Reward: {gold} gold + {xp} XP",
    "quest_reward_item":        "  Item: {item}",
    "quest_received":           "  You receive: {item}",

    "skill_tree_title":         "SKILL TREE — {class_name}",
    "skill_unlocked":           "[UNLOCKED]",
    "skill_available":          "[AVAILABLE]",
    "skill_locked":             "[LOCKED — {reason}]",
    "skill_req":                "Req: Level {level}",
    "skill_tier_base":          "BASE",
    "skill_tier_advanced":      "ADVANCED",
    "skill_tier_elite":         "ELITE",
    "skill_unlock_prompt":      "Which skill do you unlock?",
    "skill_back":               "-- Back --",
    "skill_no_available":       "[ No skills available to unlock yet. Level up first. ]",
    "skill_unlocked_msg":       "Unlocked: {name}!",
    "skill_now_available":      "  Skill is now available in combat.",

    "victory_banner":           "V I C T O R Y",
    "victory_1":                "You have conquered the Dungeons of Aethoria.",
    "victory_2":                "The final darkness has been driven back.",
    "victory_3":                "Your name will be carved into stone.",
    "victory_stats":            "FINAL STATISTICS",
    "victory_name":             "  Name   : {name}",
    "victory_class":            "  Class  : {class_name}  Lvl.{level}",
    "victory_kills":            "  Kills  : {kills}",
    "victory_gold":             "  Gold   : {gold} gp",
    "victory_press":            "[ A legend has been born. ]",
    "gameover_banner":          "G A M E   O V E R",
    "gameover_1":               "The dungeon has claimed another soul.",
    "gameover_2":               "Your bones join countless others in the dark.",
    "gameover_char":            "  {name} the {class_name} — Level {level}",
    "gameover_stats":           "  Enemies slain: {kills}  |  Floors cleared: {floors}",
    "gameover_gold":            "  Gold carried to the grave: {gold} gp",

    "credits_title":            "DUNGEONS OF AETHORIA — Credits",
    "credits_built":            "  Built with Python 3.11+",
    "credits_inspired":         "  Inspired by the text RPGs of the 80s",
    "credits_dnd":              "  and the original Dungeons & Dragons rulebooks",
    "credits_thanks":           "  Thank you for playing.",
    "credits_quote_1":          "  'Not all who wander dungeons are lost.'",
    "credits_quote_2":          "  'Most of them are. Completely.'",
    "quit_1":                   "The torch fades. The dungeon waits.",
    "quit_2":                   "Until next time, adventurer.",

    "invalid_option":           "Invalid option. Try again.",
    "press_enter":              "[ Press ENTER to continue ]",


    "class_desc_guerrero":  "Master of melee combat. Tough and powerful.",
    "class_desc_mago":      "Arcane spellcaster. Fragile but devastatingly powerful.",
    "class_desc_picaro":    "Shadow and blade. Fast, first, deadly.",
    "class_desc_paladin":   "Holy warrior. Heals allies and smites evil.",
    "class_desc_arquero":   "Ranged master. Precise, swift, lethal from afar.",
    "class_desc_barbaro":   "Pure rage. More damage the more wounded. No limits.",
    "class_desc_monje":     "Unarmed combatant. Speed and discipline over brute force.",
    "class_desc_explorador":"Tracker and trapper. Lethal by surprise, master of terrain.",
    "class_desc_hechicero": "Wild and unpredictable magic. High risk, high reward.",
    "class_desc_brujo":     "Dark pacts with ancient entities. Power at the price of blood.",

    "ab_guerrero_1_name": "Power Strike",
    "ab_guerrero_1_desc": "A devastating blow that bypasses part of the enemy's armor.",
    "ab_guerrero_2_name": "Second Wind",
    "ab_guerrero_2_desc": "Recover 30 HP when near death.",
    "ab_guerrero_3_name": "Whirlwind",
    "ab_guerrero_3_desc": "Strike all enemies in the area.",

    "ab_mago_1_name": "Fireball",
    "ab_mago_1_desc": "A blazing projectile that burns the enemy.",
    "ab_mago_2_name": "Arcane Shield",
    "ab_mago_2_desc": "A magical barrier that reduces incoming damage.",
    "ab_mago_3_name": "Chain Lightning",
    "ab_mago_3_desc": "A bolt that ignores defense and stuns the enemy.",

    "ab_picaro_1_name": "Backstab",
    "ab_picaro_1_desc": "Surprise attack with high critical damage.",
    "ab_picaro_2_name": "Poison Blade",
    "ab_picaro_2_desc": "Coat your blade in poison for damage over time.",
    "ab_picaro_3_name": "Shadow Step",
    "ab_picaro_3_desc": "Become evasive for one turn, avoiding attacks.",

    "ab_paladin_1_name": "Holy Strike",
    "ab_paladin_1_desc": "A divine-powered attack. Extra effective against undead.",
    "ab_paladin_2_name": "Divine Heal",
    "ab_paladin_2_desc": "Restore 45 HP through divine grace.",
    "ab_paladin_3_name": "Holy Aura",
    "ab_paladin_3_desc": "An aura that reduces incoming damage for 3 turns.",

    "ab_arquero_1_name": "True Shot",
    "ab_arquero_1_desc": "A precise arrow that always finds its mark.",
    "ab_arquero_2_name": "Poison Arrow",
    "ab_arquero_2_desc": "A shot that poisons the enemy.",
    "ab_arquero_3_name": "Eagle Eye",
    "ab_arquero_3_desc": "Analyze the enemy's weaknesses to boost future attacks.",

    "ab_barbaro_1_name": "Brutal Strike",
    "ab_barbaro_1_desc": "A massive blow that crushes defenses.",
    "ab_barbaro_2_name": "Rage Mode",
    "ab_barbaro_2_desc": "Enter berserker mode: more damage but no defense.",
    "ab_barbaro_3_name": "War Cry",
    "ab_barbaro_3_desc": "Terrorize the enemy, paralyzing them for one turn.",

    "ab_monje_1_name": "Chi Strike",
    "ab_monje_1_desc": "A strike of pure energy that bypasses armor.",
    "ab_monje_2_name": "Inner Healing",
    "ab_monje_2_desc": "Meditate to restore 35 HP.",
    "ab_monje_3_name": "Rain of Blows",
    "ab_monje_3_desc": "Five rapid strikes that overwhelm defenses.",

    "ab_explorador_1_name": "Hunting Trap",
    "ab_explorador_1_desc": "Set a trap that deals damage and slows.",
    "ab_explorador_2_name": "Stealth Attack",
    "ab_explorador_2_desc": "Surprise attack with double damage.",
    "ab_explorador_3_name": "Tracker's Mark",
    "ab_explorador_3_desc": "Mark the enemy to increase future damage.",

    "ab_hechicero_1_name": "Arcane Chaos",
    "ab_hechicero_1_desc": "A random spell with unpredictable effects.",
    "ab_hechicero_2_name": "Mana Drain",
    "ab_hechicero_2_desc": "Absorb the enemy's energy to heal yourself.",
    "ab_hechicero_3_name": "Chaos Storm",
    "ab_hechicero_3_desc": "A massive magical explosion with multiple effects.",

    "ab_brujo_1_name": "Dark Curse",
    "ab_brujo_1_desc": "A curse that drains the enemy's life over several turns.",
    "ab_brujo_2_name": "Blood Pact",
    "ab_brujo_2_desc": "Sacrifice your own life force for a devastating attack.",
    "ab_brujo_3_name": "Summon Shadow",
    "ab_brujo_3_desc": "Summon a shadow entity to attack in your name.",

    "room_combat":   "[ ENCOUNTER ]",
    "room_treasure": "[ TREASURE ]",
    "room_rest":     "[ REST ]",
    "room_merchant": "[ MERCHANT ]",
    "room_trap":     "[ TRAP ]",
    "room_mystery":  "[ MYSTERY ]",
    "room_boss":     "[ !! BOSS !! ]",
    "room_generic":  "[ ROOM ]",

    "floor_1":  "The upper crypts. Enemies are weak, but don't get comfortable. Never.",
    "floor_2":  "The burial halls. The dead grow restless. It gets worse.",
    "floor_3":  "The warrens. Something organized lives here and knows you've arrived.",
    "floor_4":  "The shadow galleries. Light dies here. Monsters grow bolder.",
    "floor_5":  "The deep mines. Dug by people who found something they shouldn't have.",
    "floor_6":  "The cursed vaults. Ancient evil seeps from the very stones.",
    "floor_7":  "The demon corridors. Not everyone who entered here was human.",
    "floor_8":  "The abyssal halls. Reality feels thin. Something watches from the walls.",
    "floor_9":  "The final descent. The dungeon's master waits. All paths end here.",
    "floor_10": "UNKNOWN DEPTH. Maps end here. So do legends. Do you?",

    "room_desc_combat_1": "The torch flickers. Something moves at the end of the corridor.",
    "room_desc_combat_2": "A terrible smell hits you. Something lives here and knows you've arrived.",
    "room_desc_combat_3": "Ancient bones creak under your feet. Whoever made this room still considers it theirs.",
    "room_desc_combat_4": "Low growls from the darkness. You grip your weapon. Breathe. Two out of three help.",
    "room_desc_combat_5": "Fresh scratch marks on the walls. Something with claws was here very recently.",
    "room_desc_treasure_1": "A metallic glint under the rubble. Could be gold. Could be a trap. Fifty-fifty.",
    "room_desc_treasure_2": "A carved stone chest, untouched, iron latch intact. No one opened it. That's either good or very bad.",
    "room_desc_treasure_3": "The remains of an unluckier adventurer. Their gear is still here. The dead don't use equipment.",
    "room_desc_treasure_4": "A loose stone reveals a hidden hollow. Inside: opportunity. Or spiders. Probably both.",
    "room_desc_rest_1": "A dry corner with the remains of an old campfire. Safe as a Sunday afternoon.",
    "room_desc_rest_2": "Clean water drips from a crack in the stone. Cold, clear, and in this place, almost miraculous.",
    "room_desc_rest_3": "The dungeon opens into a quiet chamber. For a moment, nothing wants to kill you. Enjoy it.",
    "room_desc_merchant_1": "A figure behind an improvised stall, perfectly calm in the middle of a dungeon.",
    "room_desc_merchant_2": "A merchant caravan. Here. In the dungeon corridor. No explanation. Apparently it works.",
    "room_desc_trap_1": "The floor is very smooth. Too smooth. In a dungeon, that's not a good sign.",
    "room_desc_trap_2": "Thin wires catch the torchlight. You stop dead. Suddenly very careful.",
    "room_desc_trap_3": "A pressure plate bears an inscription in three dead languages: 'Turn back'. Clear message.",
    "room_desc_mystery_1": "A strange altar in the center of the room, symbols pulsing with dim light.",
    "room_desc_mystery_2": "A mirror leaning against the wall. Your reflection doesn't move at the same time as you.",
    "room_desc_mystery_3": "Words carved into the floor: 'Choose wisely. Or simply don't choose.' Dungeon philosophy.",
    "room_desc_boss": "At the end of a long corridor, enormous doors stand ajar. Something breathes on the other side.",

    "combat_start":         "  [ Combat begins... ]",
    "combat_turn":          "Turn",
    "combat_your_action":   "Your turn",
    "combat_enter_combat":  "Enter combat",
    "combat_check_inv":     "Check inventory first",
    "combat_ability_prompt":"Ability",
    "combat_use_potion":    "Use potion",
    "combat_cancel":        "-- Cancel --",
    "combat_quick_status":  "QUICK STATUS",
    "combat_status_rest":   "REST STATUS",
    "combat_merchant_title":"DUNGEON MERCHANT",
    "combat_buy":           "Buy",
    "combat_sell":          "Sell",
    "combat_exit":          "Leave",
    "combat_buy_prompt":    "Buy",
    "combat_sell_prompt":   "Sell",
    "combat_gold_label":    "Your Gold",
    "combat_heal_recover":  "You recover {n} HP.",

    "inv_empty_msg":        "Your pack is empty. Nothing at all.",
    "inv_close":            "-- Close --",
    "inv_select":           "Which item?",
    "inv_action_use":       "Use now",
    "inv_action_equip":     "Equip",
    "inv_action_drop":      "Discard (gone)",
    "inv_action_cancel":    "Cancel",
    "inv_action_prompt":    "What do you do with this?",
    "inv_dropped":          "You discard the {item}.",
    "inv_empty_slot":       "-- empty --",
    "inv_weapon_label":     "Weapon",
    "inv_armor_label":      "Armor",
    "inv_ring_label":       "Ring",
    "inv_rarity_label":     "Rarity",
    "inv_heal_label":       "Heals",
    "inv_mana_label":       "Mana",


    "ui_clase_header":     "  {'CLASS':<14} {'HP':>4} {'MP':>4} {'Primary':<10} {'Description'}",
    "ui_base_stats":       "  BASE STATS",
    "ui_abilities":        "  ABILITIES",
    "ui_attributes":       "  ATTRIBUTES",
    "ui_start_weapon":     "  Starting weapon",
    "ui_start_armor":      "  Starting armor",
    "ui_stat_primary":     "Primary stat",
    "ui_equipped_weapon":  "  Weapon",
    "ui_equipped_armor":   "  Armor",
    "ui_equipped_ring":    "  Ring",
    "ui_class_label":      "CLASS",
    "ui_hp_label":         "HP",
    "ui_mp_label":         "MP",
    "ui_principal_label":  "Primary",
    "ui_desc_label":       "Description",
    "ui_nivel_label":      "Level",
    "ui_oro_label":        "Gold",
    "ui_bajas_label":      "Kills",
    "ui_pisos_label":      "Floors",
    "ui_habilidades_label":"Skills",
    "ui_misiones_label":   "Quests",

    "lore_guerrero":  "Born in battle and hardened by countless wars. More scars than stories, and more stories than most. Doesn't think much. Doesn't need to.",
    "lore_mago":      "Twenty years in the Arcane Tower, and never found work in the field. Now throws fireballs in a dungeon. Could be worse.",
    "lore_picaro":    "Grew up in the rough quarter and learned early: strike first, strike hard. Operates from shadows — which is basically just doing everything at the last second, but with more drama.",
    "lore_paladin":   "Took the solemn oath to defend the Light. Mostly keeps it. The undead fear them. The living do too, for different reasons. A bit intense at social gatherings.",
    "lore_arquero":   "Grew up in the deep forest and never really left. Eats wild berries, speaks little, shoots better than anyone. Don't invite them to parties — they'll appear from behind a tree.",
    "lore_barbaro":   "Comes from a very cold place with not much to do besides get angry. Has no strategy. Doesn't need one. The plan is to keep moving forward until something stops. Usually not him.",
    "lore_monje":     "Meditated ten thousand hours to find inner peace. Found it. Turns out inner peace looks a lot like five consecutive punches to the face. Deep philosophy.",
    "lore_explorador":"Reads the dungeon like a map: knows exactly when danger is coming, where the exits are, and which corridor smells worst. Prefers working alone. Others make noise.",
    "lore_hechicero": "Magic came naturally, without studying. Made classmates nervous. Doesn't fully control what they do. Works out 65% of the time. The other 35% is also interesting.",
    "lore_brujo":     "Prayed to something in the darkness and it answered. Doesn't know what it was. Prefers not to ask. Rent doesn't pay itself, and dark pacts have better terms than banks.",

    "desc_goblin":         "A scrawny, green-skinned creature clutching a rusty knife. Looks like it hasn't eaten in days. Still going to attack you.",
    "desc_goblin_shaman":  "A hunched goblin adorned with bones and fetishes. Clearly the intellectual of the group. Doesn't make it less dangerous, just weirder.",
    "desc_giant_rat":      "A rat the size of a medium dog. Found it in the dungeon, but it could easily be from any city subway line.",
    "desc_skeleton":       "Bones held together by dark magic and a bad attitude. The knife is more rust than blade. Still hurts.",
    "desc_orc":            "A massive, tusked brute in iron armor that clearly hasn't been cleaned in years. Smells like blood and something you'd rather not identify.",
    "desc_dark_elf":       "A lithe figure in black silk, twin blades gleaming with poison. Better dressed than you. Much better. That stings too, but differently.",
    "desc_zombie_knight":  "Once noble, now a rotting horror in rusted plate. Still has more bearing than most. Death did not strip it of its posture, unfortunately.",
    "desc_dungeon_witch":  "A cackling hag wreathed in green smoke, cauldron bubbling with something that definitely isn't tea. Clearly doing well for herself.",
    "desc_vampire":        "Pale, cold, and insufferably superior. Centuries of experience making you feel lesser. Like that one coworker, but with fangs.",
    "desc_stone_golem":    "Eight feet of animated granite, runes blazing across its chest. It doesn't run. It doesn't speak. It doesn't negotiate. It simply walks toward you. Calmly.",
    "desc_lesser_demon":   "A creature of flame and pure hatred, wings like burned leather. Eyes like coals, and the attitude of someone whose flight was cancelled and luggage lost.",
    "desc_dragon":         "An enormous dragon. Seriously, it's BIG. Bigger than you're imagining. You spent the whole dungeon thinking the finale would be manageable. Miscalculation.",
    "desc_lich":           "Once the greatest wizard in the world, chose immortality. Now a skeleton with attitude. Dying would have been more elegant, but nobody asked.",
    "desc_archfiend":      "The dungeon's true master. Three centuries sealed down here. In a bad mood, understandably. You're the first thing it'll see on the way out. Bad timing.",
}


STRINGS = {
    "es": _ES,
    "en": _EN,
}

AVAILABLE_LANGUAGES = {
    "es": "Español",
    "en": "English",
}
